chore: added helm chart
MapColonies/layer-spec pull request #2
Opened 2021-09-14 10:42 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     |✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                      |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-09-19 07:00 UTC, asafMasa requested changes
:+1:

2021-09-19 07:00 UTC, asafMasa commented on helm/Chart.yaml
> +description: "layer spec app deployement"
Why do you need "" ?

2021-09-19 07:00 UTC, asafMasa commented on helm/values.yaml
> +  imagePullPolicy: Always
check with yossi

2021-09-19 07:00 UTC, asafMasa commented on helm/values.yaml
> +  tag: latest
tag should have ''?

2021-09-19 07:00 UTC, asafMasa commented on openapi3.yaml
> -            format: uuid
why?

2021-09-26 08:59 UTC, CL-SHLOMIKONCHA commented on openapi3.yaml
> -            format: uuid
fixed in 9489fb6

2021-09-26 08:59 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  tag: latest
fixed in 9489fb6

2021-09-26 08:59 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  imagePullPolicy: Always
removed for now in 9489fb6

2021-09-26 08:59 UTC, CL-SHLOMIKONCHA commented on helm/Chart.yaml
> +description: "layer spec app deployement"
fixed in 9489fb6

2021-09-29 07:59 UTC, asafMasa approved these changes

2021-09-29 07:59 UTC, asafMasa commented on helm/templates/postgres-secrect.yaml
> +{{- end }}
update

2021-09-29 09:04 UTC, yossiz16 requested changes

2021-09-29 09:04 UTC, yossiz16 commented on helm/Chart.yaml
> +description: "layer spec app deployement"
layer spec chart

2021-09-29 09:04 UTC, yossiz16 commented on helm/templates/configmap.yaml
> +  DB_PORT: {{ .Values.env.db.port | quote }}
remove quote

2021-09-29 09:04 UTC, yossiz16 commented on helm/templates/ingress.yaml
>  {{- $releaseName := .Release.Name -}}
remove if no necccery

2021-09-29 09:04 UTC, yossiz16 commented on helm/templates/postgres-secrect.yaml
> +{{- end }}
add empty space

2021-09-29 09:04 UTC, yossiz16 commented on helm/templates/route.yaml
>  {{- $releaseName := .Release.Name -}}
remove

2021-09-30 11:49 UTC, CL-SHLOMIKONCHA commented on helm/Chart.yaml
> +description: "layer spec app deployement"
fixed

2021-09-30 11:49 UTC, CL-SHLOMIKONCHA commented on helm/Chart.yaml
> +description: "layer spec app deployement"
fixed

2021-09-30 11:50 UTC, CL-SHLOMIKONCHA commented on helm/templates/configmap.yaml
> +  DB_PORT: {{ .Values.env.db.port | quote }}
removed

2021-09-30 12:03 UTC, CL-SHLOMIKONCHA commented on helm/templates/postgres-secrect.yaml
> +{{- end }}
fixed

2021-09-30 12:03 UTC, CL-SHLOMIKONCHA commented on helm/templates/ingress.yaml
>  {{- $releaseName := .Release.Name -}}
necessary

2021-09-30 12:07 UTC, CL-SHLOMIKONCHA commented on helm/templates/route.yaml
>  {{- $releaseName := .Release.Name -}}
necessary

2021-10-03 07:31 UTC, yossiz16 approved these changes

2021-10-05 10:43 UTC, merged